version: 1.0.{build}
image: Visual Studio 2017

before_build:
  - dotnet restore

build:
  verbosity: minimal
  project: CASCExplorer.sln

clone_script:
  - cmd: >-
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
